// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/audit" | "/connectors" | "/employees" | "/employees/[id]" | "/employees/[id]/sessions" | "/employees/[id]/tools/[provider]" | "/hourly/[id]" | "/leaderboard" | "/login" | "/my-connectors" | "/platform" | "/platform/[orgId]/audit" | "/platform/[orgId]/connectors" | "/platform/[orgId]/employees" | "/platform/[orgId]/employees/[id]" | "/platform/[orgId]/employees/[id]/sessions" | "/platform/[orgId]/employees/[id]/tools/[provider]" | "/platform/[orgId]/hourly/[id]" | "/platform/[orgId]/leaderboard" | "/platform/[orgId]/overview" | "/platform/[orgId]/policy" | "/platform/[orgId]/sessions/[id]" | "/platform/[orgId]/users" | "/policy" | "/sessions/[id]" | "/setup-connector" | "/users"
type PageRoutes = never
type LayoutRoutes = "/" | "/platform/[orgId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/audit": {}
  "/connectors": {}
  "/employees": {}
  "/employees/[id]": { "id": string; }
  "/employees/[id]/sessions": { "id": string; }
  "/employees/[id]/tools/[provider]": { "id": string; "provider": string; }
  "/hourly/[id]": { "id": string; }
  "/leaderboard": {}
  "/login": {}
  "/my-connectors": {}
  "/platform": {}
  "/platform/[orgId]": { "orgId": string; }
  "/platform/[orgId]/audit": { "orgId": string; }
  "/platform/[orgId]/connectors": { "orgId": string; }
  "/platform/[orgId]/employees": { "orgId": string; }
  "/platform/[orgId]/employees/[id]": { "orgId": string; "id": string; }
  "/platform/[orgId]/employees/[id]/sessions": { "orgId": string; "id": string; }
  "/platform/[orgId]/employees/[id]/tools/[provider]": { "orgId": string; "id": string; "provider": string; }
  "/platform/[orgId]/hourly/[id]": { "orgId": string; "id": string; }
  "/platform/[orgId]/leaderboard": { "orgId": string; }
  "/platform/[orgId]/overview": { "orgId": string; }
  "/platform/[orgId]/policy": { "orgId": string; }
  "/platform/[orgId]/sessions/[id]": { "orgId": string; "id": string; }
  "/platform/[orgId]/users": { "orgId": string; }
  "/policy": {}
  "/sessions/[id]": { "id": string; }
  "/setup-connector": {}
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/platform/[orgId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
