// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../src/app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/connectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connectors">> = Specific
  const handler = {} as typeof import("../../src/app/connectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/[id]/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/employees/[id]/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/[id]/tools/[provider]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]/tools/[provider]">> = Specific
  const handler = {} as typeof import("../../src/app/employees/[id]/tools/[provider]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../src/app/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hourly/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hourly/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/hourly/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/my-connectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-connectors">> = Specific
  const handler = {} as typeof import("../../src/app/my-connectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/audit">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/connectors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/connectors">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/connectors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/employees/[id]/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/employees/[id]/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/employees/[id]/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/employees/[id]/tools/[provider]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/employees/[id]/tools/[provider]">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/employees/[id]/tools/[provider]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/employees">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/hourly/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/hourly/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/hourly/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/overview">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/policy">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/sessions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/sessions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/[orgId]/users">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../src/app/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy">> = Specific
  const handler = {} as typeof import("../../src/app/policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sessions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/sessions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/setup-connector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup-connector">> = Specific
  const handler = {} as typeof import("../../src/app/setup-connector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../src/app/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/platform/[orgId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/platform/[orgId]">> = Specific
  const handler = {} as typeof import("../../src/app/platform/[orgId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
